src/credit_lecture_system/urls.py
from django.contrib import admin
from django.urls import path, include
from lecture.views import LectureViewSet
from user.views import ClassViewSet
from rest_framework import routers
router = routers.DefaultRouter()
router.register('lectures', LectureViewSet)
router.register('class', ClassViewSet)
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('lecture.urls')),
    path('user/',include('user.urls')),
    path('api/', include(router.urls), name='api')
]

src/lecture/urls.py
from django.urls import path,include
from .views import (
    index_view,
    lecture_create_view,
    lecture_signup_view,
    detail_view,
    LectureViewSet,
    lecture_draw_view
    )


app_name = 'lecture'
urlpatterns = [
    path('', index_view, name='index'),
    path('<int:id>/', detail_view,name='detail'),
    path('create',lecture_create_view,name='create'),
    path('<int:lecture_id>/signup/', lecture_signup_view,name='signup'),
    path('<int:lecture_id>/draw', lecture_draw_view, name='draw')
]

src/user/urls.py
from django.urls import path,include
from .views import (
    index_view,
    sign_out_view,
    login_view
)
app_name = 'user'
urlpatterns = [
    path('', index_view, name='index'),
    path('signout/', sign_out_view, name='signout'),
    path('login/', login_view, name='login')
]

src/lecture/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from user.models import Class
from django.utils.translation import gettext_lazy as _
# Create your models here.


class Lecture(models.Model):
    title = models.CharField(max_length=120)
    lecture_time = models.DateTimeField()
    draw_date = models.DateField(blank=False, null=False)
    introduction = models.TextField(blank=True, null=False)
    capacity = models.IntegerField()
    lecture_location = models.TextField()
    lecturer = models.TextField()
    lecturer_introduction = models.TextField()
    target_class = models.ManyToManyField(Class, blank=True)
    did_draw = models.BooleanField(blank=False, default=False)

    class Meta:
        ordering = ['-lecture_time']

    def get_absolute_url(self):
        return reverse("lecture:detail", kwargs={"id": self.id})

    def __str__(self):
        return self.title

    def get_change_url(self):
        info = (self._meta.app_label, self._meta.model_name)
        return reverse('admin:%s_%s_change' % info, args=(self.id,))

    @property
    def get_number_of_selected(self):
        results = DrawResult.objects.all().filter(lecture=self)
        if self.did_draw:
            return len(results.filter(draw_status=DrawResult.Status.WIN))
        else:
            return len(results)


class AttendanceLog(models.Model):

    lecture = models.OneToOneField(Lecture, on_delete=models.CASCADE)
    student = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    didAttend = models.BooleanField('Attendance', default=False)

    def __str__(self):
        return self.lecture.title + ": " + self.student.username + ' Attend: ' + self.didAttend

    class Meta:
        ordering = ['student']


class DrawResult(models.Model):
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE,unique=False,primary_key=False)
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,unique=False,primary_key=False)

    class Meta:
        unique_together = ('lecture', 'student')
        ordering = ['lecture']

    class Status(models.TextChoices):
        PENDING = 'PEN',_('Pending')
        WIN = 'WIN',_("Win")
        MISSED = 'MIS',_('Missed')

    draw_status = models.CharField(max_length=3, choices=Status.choices, default=Status.PENDING, null=False)

    def get_status(self):
        if self.draw_status == self.Status.WIN:
            return "中选"
        elif self.draw_status == self.Status.MISSED:
            return "落选"
        elif self.draw_status == self.Status.PENDING:
            return "等待抽选"
        else:
            raise KeyError

    def __str__(self):
        return str(self.lecture) + '-' + str(self.student) + '-' + self.get_status()

src/lecture/forms.py
from django import forms
from .models import Lecture
from datetime import datetime


class LectureForm(forms.ModelForm):
    title = forms.CharField(label='Title')
    lecture_time = forms.DateTimeField(label='Time:', initial=datetime.now)
    introduction = forms.CharField(label='introduction')
    capacity = forms.IntegerField()
    lecture_location = forms.CharField()
    lecturer = forms.CharField()
    lecturer_introduction = forms.CharField()
    draw_time = forms.DateTimeField(label='Time', initial=datetime.now)

    class Meta:
        model = Lecture
        fields = [
            'title',
            'lecture_time',
            'introduction',
            'capacity',
            'lecture_location',
            'lecturer',
            'lecturer_introduction',
            'draw_time'
        ]

src/lecture/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from .models import *
from .forms import LectureForm
from rest_framework import viewsets
from .serializers import LectureSerializer
from django.db import IntegrityError
from random import shuffle


# List view of lectures
def index_view(request):
    lectures = Lecture.objects.order_by('lecture_time')
    paginator = Paginator(lectures, 6) # Show 12 lectures per page
    page_number = request.GET.get('page')
    lectures = paginator.get_page(page_number)
    selected_lectures = []
    if request.user.is_authenticated:
        selected_results = DrawResult.objects.all().filter(student=request.user)
        for result in selected_results:
            selected_lectures.append(result.lecture)
    context = {
        'lectures': lectures,
        'selected_lectures': selected_lectures
    }
    return render(request, 'lecture_list.html', context)


def detail_view(request, id):
    lecture = get_object_or_404(Lecture, id=id)

    context = {
        'lecture': lecture
    }

    return render(request, 'lecture_detail.html', context)


def lecture_create_view(request):
    form = LectureForm(request.POST or None)
    if form.is_valid():
        lecture = form.save()
        form = LectureForm()

    context = {
        'form': form
    }
    return render(request, 'lecture_create.html', context)


def lecture_signup_view(request, lecture_id):
    if request.user.is_anonymous:
        return redirect('user:login')
    lecture = get_object_or_404(Lecture, pk=lecture_id)
    if lecture.did_draw: # If a lecture is already drawn then we can not signup.
        return redirect('lecture:index')
    record = DrawResult()
    record.lecture = lecture
    record.student = request.user
    try:
        record.save()
    except IntegrityError:
        return redirect('lecture:index')

    return redirect('user:index')


def lecture_draw_view(request, lecture_id):
    if not request.user.is_staff:
        return redirect('lecture:index')
    success = draw(lecture_id)  # TODO: do different thing if fails to draw.
    return redirect('lecture:index')


def draw(lecture_id) -> bool:
    try:
        lecture = Lecture.objects.get(id=lecture_id)
    except ObjectDoesNotExist:
        return False
    if lecture.did_draw:
        return False
    results = DrawResult.objects.all().filter(lecture=lecture)
    # If the number of student signed up for the lecture is smaller than its capacity, all students can go.
    if len(results) <= lecture.capacity:
        for result in results:
            result.draw_status = DrawResult.Status.WIN
            result.save()

    # TODO: For now, all students have the same probability to get in the lecture.
    #  We need to implement the target class logic.
    else:
        results = list(results)
        shuffle(results)
        for i in range(lecture.capacity):
            results[i].draw_status = DrawResult.Status.WIN
            results[i].save()
        for i in range(lecture.capacity, len(results)):  # TODO: Fix efficiency here.
            results[i].draw_status = DrawResult.Status.MISSED
            results[i].save()
    lecture.did_draw = True
    lecture.save()
    return True


class LectureViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Lecture.objects.all().order_by('lecture_time')
    serializer_class = LectureSerializer

src/lecture/templates/lecture_create.html
{% extends 'base.html' %}
    {% block content %}
    <form action="./create" method="POST"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
    {% endblock %}

src/lecture/templates/lecture_detail.html
{% extends 'base.html' %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'lecture:index' %}">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a href="#">Detail</a>
    </li>
{% endblock %}

{% block content %}

{% if lecture %}
    {% autoescape off %}
        <div class="jumbotron container-fluid">
        <div class="col-md-3">
            <h4>{{ lecture.id }}{{ lecture.title }}</h4>
            <p class="text-left">
            Time: {{ lecture.lecture_time }} <br/>
            Introduction: {{ lecture.introduction }} <br/>
            Capacity: {{ lecture.capacity }}<br/>
{#            TODO: Show how many person have already signed up for the lecture.#}
            Location: {{ lecture.lecture_location }}<br/>
            Lecturer: {{ lecture.lecturer }}<br/>
            Lecturer Introduction: {{ lecture.lecturer_intoduction }} <br/>
        </p>
        </div>
        </div>
        <form method="post" action="{% url 'lecture:signup' lecture.id %}"> {% csrf_token %}
            <input type="hidden" name="lecture_id" id="{{ lecture.id }}"  value="{{ lecture.id }}">
            <input type="submit" class="btn btn-primary center-block" value="SIGNUP">
        </form>

    {% endautoescape %}
{% else %}
    <p>No lecture to be shown.</p>
    <br/>
{% endif %}
{% endblock %}

src/lecture/templates/lecture_list.html
{% extends 'base.html' %}
{% load admin_urls %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a class="nav-link" href="{% url 'lecture:index' %}">Home</a>

    </li>

{% endblock %}
{% block content %}
{% if lectures %}
    <div class="col-12">
    <div class="row ">
    {% for lecture in lectures %}
        {% autoescape off %}
        <div class="col-lg-4 col-md-12 mb-3">
            <div class="card">
            <div class="card-body">
              <h5 class="card-title">
                <a href="{% url 'lecture:detail' lecture.id %}">
                  <u>{{ lecture.title }}</u>
                </a>
              </h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">简介： {{ lecture.introduction }}</li>
                    <li class="list-group-item">时间: {{ lecture.lecture_time }}</li>
                    <li class="list-group-item">地点: {{ lecture.lecture_location }}</li>

                    <li class="list-group-item">演讲人: {{ lecture.lecturer }}
                        <br/>
                        {{ lecture.lecturer_introduction }}
                    </li>
                    <li class="list-group-item">选课人数: {{ lecture.get_number_of_selected }}/{{ lecture.capacity }}</li>
                    <li class="list-group-item">
                        {% if request.user.is_staff %}
                            <div class="btn-group">
                                <a href="{{ lecture.get_change_url }}" class="btn btn-primary m-auto">修改</a>
                                <a href="#" class="btn btn-danger m-auto">删除</a>
                                <a href="{% url 'lecture:draw' lecture.id %}" class="btn btn-info m-auto {% if lecture.did_draw %} disabled{% endif %}">抽选</a>
                            </div>
                        {% else %}
                            {% if selected_lectures and lecture in selected_lectures %}
                                 <a href="{% url 'lecture:signup' lecture.id %}" class="btn btn-danger m-auto {% if lecture.did_draw %}disabled{% endif %}">退选</a>
                            {% else %}
                                <a href="{% url 'lecture:signup' lecture.id %}" class="btn btn-primary m-auto">报名</a>
                            {% endif %}
                        {% endif %}
                    </li>
                </ul>
            </div>
            </div>
            <div class="clearfix"></div>
        </div>


        {% endautoescape %}
    {% endfor %}
    </div>
    <div class="pagination center-block">
    <span class="step-links">
        {% if lectures.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ lectures.number }} of {{ lectures.paginator.num_pages }}.
        </span>

        {% if lectures.has_next %}
            <a href="?page={{ lectures.next_page_number }}">next</a>
            <a href="?page={{ lectures.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

    {% if request.user.is_staff %}
        <a href="create" class="btn btn-primary">Create A Lecture</a>
    {% endif %}
    </div>
{% else %}
    <p class="text-center">
        当前没有讲座
    </p>
    <a class="btn btn-primary text-center" href="{% url 'lecture:create' %}">
        添加讲座
    </a>
{% endif %}
{% endblock %}