src/credit_lecture_system/urls.py
from django.contrib import admin
from django.urls import path, include
from lecture.views import LectureViewSet
from user.views import ClassViewSet
from rest_framework import routers
router = routers.DefaultRouter()
router.register('lectures', LectureViewSet)
router.register('class', ClassViewSet)
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('lecture.urls')),
    path('user/',include('user.urls')),
    path('api/', include(router.urls), name='api')
]

src/lecture/urls.py
from django.urls import path,include
from .views import (
    index_view,
    lecture_create_view,
    lecture_signup_view,
    detail_view,
    LectureViewSet,
    lecture_draw_view
    )


app_name = 'lecture'
urlpatterns = [
    path('', index_view, name='index'),
    path('<int:id>/', detail_view,name='detail'),
    path('create',lecture_create_view,name='create'),
    path('<int:lecture_id>/signup/', lecture_signup_view,name='signup'),
    path('<int:lecture_id>/draw', lecture_draw_view, name='draw')
]

src/user/urls.py
from django.urls import path,include
from .views import (
    index_view,
    sign_out_view,
    login_view
)
app_name = 'user'
urlpatterns = [
    path('', index_view, name='index'),
    path('signout/', sign_out_view, name='signout'),
    path('login/', login_view, name='login')
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>学分讲座-数学与统计学院</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>

<body>
    <div class="wrapper container-fluid">
        <!-- Sidebar  -->
        <nav id="sidebar" class="col">
            <div class="sidebar-header">
                <h3>学分讲座系统</h3>
            </div>

            <ul class="list-unstyled components">
                <p>菜单</p>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'lecture:index' %}">讲座</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content" class="col">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>菜单</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            {% if request.user.is_authenticated %}
                                <li class="nav-item active">
                                    {% if request.user.is_staff %}
                                        <a class="nav-link" href="{% url 'admin:index' %}">后台管理</a>
                                    {% else %}
                                        <a class="nav-link" href="{% url 'user:index' %}">我的课程</a>
                                    {% endif %}
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'user:signout' %}">退出</a>
                                </li>
                            {% else %}
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'user:login' %}">登陆</a>
                                </li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            </nav>

            <div class="container-fluid">
            <ol class="breadcrumb">

                {% block breadcrumb %}
                    Replace breadcrumb
                {% endblock %}
            </ol>
                {% block content %}
                    Replace content
                {% endblock %}
            </div>
        </div>
    </div>

    {#    JQuert#}
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Popper.JS -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'js/bootstrap.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>

</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学分讲座管理系统</title>
</head>
<body>
</body>
</html>