src/credit_lecture_system/urls.py
from django.contrib import admin
from django.urls import path, include
from lecture.views import LectureViewSet
from user.views import ClassViewSet
from rest_framework import routers
router = routers.DefaultRouter()
router.register('lectures', LectureViewSet)
router.register('class', ClassViewSet)
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('lecture.urls')),
    path('user/',include('user.urls')),
    path('api/', include(router.urls), name='api')
]

src/lecture/urls.py
from django.urls import path,include
from .views import (
    index_view,
    lecture_create_view,
    lecture_signup_view,
    detail_view,
    LectureViewSet,
    lecture_draw_view
    )


app_name = 'lecture'
urlpatterns = [
    path('', index_view, name='index'),
    path('<int:id>/', detail_view,name='detail'),
    path('create',lecture_create_view,name='create'),
    path('<int:lecture_id>/signup/', lecture_signup_view,name='signup'),
    path('<int:lecture_id>/draw', lecture_draw_view, name='draw')
]

src/user/urls.py
from django.urls import path,include
from .views import (
    index_view,
    sign_out_view,
    login_view
)
app_name = 'user'
urlpatterns = [
    path('', index_view, name='index'),
    path('signout/', sign_out_view, name='signout'),
    path('login/', login_view, name='login')
]

src/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
# Create your models here.


class Class(models.Model):
    grade = models.IntegerField(default=datetime.now().year + 3)
    major = models.CharField(max_length=100)
    class_number = models.CharField(max_length=50)

    def __str__(self):
        return str(self.grade) + "级" + self.major + self.class_number + "班"

    class Meta:
        ordering = ['grade', 'major']


class LectureUser(AbstractUser):
    username = None
    student_id = models.IntegerField(null=False, blank=False, unique=True, primary_key=True)
    email = models.EmailField(_('email address'))
    USERNAME_FIELD = 'student_id'
    objects = CustomUserManager()
    student_class = models.ForeignKey(Class, on_delete=models.CASCADE, null=True)

    # WeChat OpenID. We temporarily set the maximum length of it to 128
    openID = models.CharField(null=True, max_length=128)

    def __str__(self):
        return str(self.student_id)

    class Meta:
        ordering = ['student_class']

src/user/views.py
from django.shortcuts import render, HttpResponse,redirect
from django.contrib.auth import logout, authenticate, login
from lecture.models import DrawResult
from rest_framework import viewsets
from .models import Class
from .serializers import ClassSerializer

# Create your views here.
def index_view(request):
    if request.user.is_anonymous:
        redirect('user:login')
    draw_results = DrawResult.objects.all().filter(student=request.user)
    # TODO: Now, this only works when the user is student, come up with
    #  some other function when the user is staff

    # print(lecture_list)
    context = {
        'results': draw_results
    }
    return render(request,'lecture_chosen.html', context)


def sign_out_view(request):
    logout(request)
    return redirect('user:login')


def login_view(request):
    if request.method == 'POST':
        try:
            student_id = request.POST['id']
            password = request.POST['passcode']
            user = authenticate(request,username=student_id,password=password)
            if user is not None and user.is_active:
                login(request,user)
                return redirect('lecture:index')
        except KeyError:
            return redirect('user:login')

    return render(request,'login_page.html')


class ClassViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Class.objects.all().order_by('lecture_time')
    serializer_class = ClassSerializer

src/user/templates/lecture_chosen.html
{% extends 'base.html' %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'lecture:index' %}">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a href="#">我的选课</a>
    </li>

{% endblock %}
{% block content %}
{% if results %}
    <div class="col-12">
    <div class="row card-columns">

    {% for result in results %}
        {% with lecture=result.lecture %}
        {% autoescape off %}
        <div class="col-lg-3 col-md-12 m-auto">
            <div class="card">
            <div class="card-body">
              <h5 class="card-title">
                <a href="{% url 'lecture:detail' result.lecture.id %}">
                  <u>{{ lecture.title }}</u>
                </a>
              </h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">时间: {{ lecture.lecture_time }}</li>
                    <li class="list-group-item">地点: {{ lecture.lecture_location }}</li>

                    <li class="list-group-item">演讲人: {{ lecture.lecturer }}
                        <br/>
                        {{ lecture.lecturer_introduction }}
                    </li>
                    <li class="list-group-item">选课人数: {{ lecture.get_number_of_selected }}/{{ lecture.capacity }}</li>
                    <li class="list-group-item text-info">
                        抽选状态: {{ result.get_status }}
                    </li>
                    <li class="list-group-item">
                        {% if request.user.is_staff %}
                            <div class="btn-group">
                                <button href="" class="btn btn-primary m-auto">修改</button>
                                <button href="" class="btn btn-danger m-auto">删除</button>
                                <button href="" class="btn btn-info m-auto">抽选</button>
                            </div>
                        {% else %}
                            {% if lecture.did_draw %}
                            {% else %}
                                <button href="" class="btn btn-danger m-auto">退选</button>
                            {% endif %}
                        {% endif %}
                    </li>
                </ul>
            </div>
            </div>
        </div>


        {% endautoescape %}
        {% endwith %}
    {% endfor %}

    </div>
    {% if request.user.is_staff %}
        <a href="create" class="btn btn-primary">Create A Lecture</a>
    {% endif %}
    </div>

{% else %}

{% endif %}

{% endblock %}

src/user/templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>学分讲座系统-登陆</title>
</head>

    <link rel="stylesheet" href="{% static './css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static './css/main.css' %}">
    <style>
        html, body {
            height: 100%;
            width: 100%;
            background: #de5e51;
            /*background: white;*/
        }
    </style>
<body>
    <div class="container-fluid" id="root" style="height: 100%; width: 100%">
        <section class="h-100">
            <div class="container h-100">
                <div class="row justify-content-md-center h-100">

                    <div class="container-fluid card-wrapper center-block ">

                        <div class="card fat mt-5 pt-5">
                            <div class="card-body">
                                <h4 class="card-title text-center">Authentication</h4>
                                <form method="POST" action="{% url 'user:login' %}"> {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id">学号</label>
                                        <input id="id" class="form-control" type="text" name="id" autocomplete="off" required/>
                                        <label for="passcode">密码</label>
                                        <input id="passcode" class="form-control $is_valid" type="password" name="passcode" autocomplete="off" required/>
                                        <!--   输入框                                     -->
                                        <div class="invalid-feedback">Wrong passcode, try again please.</div>
                                    </div>
                                    <div class="form-group m-0">

                                        <button class="btn btn-primary btn-block" id = submitbtn>
                                            GO!
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="{% static './js/jquery.min.js' %}"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>